// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Stalker.Gamma.Proxies.PythonApiClient.Livez;
using Stalker.Gamma.Proxies.PythonApiClient.Navigate;
using Stalker.Gamma.Proxies.PythonApiClient.Readyz;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Stalker.Gamma.Proxies.PythonApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PythonApiClient : BaseRequestBuilder
    {
        /// <summary>The livez property</summary>
        public global::Stalker.Gamma.Proxies.PythonApiClient.Livez.LivezRequestBuilder Livez
        {
            get => new global::Stalker.Gamma.Proxies.PythonApiClient.Livez.LivezRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The navigate property</summary>
        public global::Stalker.Gamma.Proxies.PythonApiClient.Navigate.NavigateRequestBuilder Navigate
        {
            get => new global::Stalker.Gamma.Proxies.PythonApiClient.Navigate.NavigateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The readyz property</summary>
        public global::Stalker.Gamma.Proxies.PythonApiClient.Readyz.ReadyzRequestBuilder Readyz
        {
            get => new global::Stalker.Gamma.Proxies.PythonApiClient.Readyz.ReadyzRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Stalker.Gamma.Proxies.PythonApiClient.PythonApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PythonApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
