// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Stalker.Gamma.Proxies.PythonApiClient.Readyz
{
    [Obsolete("This class is obsolete. Use ReadyzGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReadyzResponse : global::Stalker.Gamma.Proxies.PythonApiClient.Readyz.ReadyzGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Stalker.Gamma.Proxies.PythonApiClient.Readyz.ReadyzResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Stalker.Gamma.Proxies.PythonApiClient.Readyz.ReadyzResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Stalker.Gamma.Proxies.PythonApiClient.Readyz.ReadyzResponse();
        }
    }
}
#pragma warning restore CS0618
